name = vlf_cozy
title = Voxelforge /sit and lay commands
description = Sit and lay using chat commands
depends = mcl_player, mcl_playerinfo, playerphysics
optional_depends = mcl_title
author = VoxelForge
